### ISSUE TITLE
pygstc.gstcerror.GstdError: Bad pipeline description

### ISSUE THREAD

**Issue by xiaomaozhou26** [RidgeRun/gtc-2020-demo#3]
When running the example on Jetson TX2, I got the following error. Any help?
nvarguscamerasrc ! nvvidconv ! video/x-raw,format=I420,width=1280,height=720 ! queue ! interpipesink name=camera1 forward-events=true forward-eos=true sync=false
Creating pipeline: camera1

Traceback (most recent call last):
  File "media.py", line 44, in <module>
    camera1 = PipelineEntity(client, 'camera1', 'nvarguscamerasrc ! nvvidconv ! video/x-raw,format=I420,width=1280,height=720 ! queue ! interpipesink name=camera1 forward-events=true forward-eos=true sync=false')
  File "media.py", line 14, in __init__
    self._client.pipeline_create(self._name, self._description)
  File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 805, in pipeline_create
    self._send_cmd_line(['pipeline_create'] + parameters)
  File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 240, in _send_cmd_line
    raise GstdError(result['description'])
pygstc.gstcerror.GstdError: Bad pipeline description

**Comment by fischer** [comment]
When you get a "Bad pipeline description" error, you can use gst-launch to verify you pipeline.  I don't have Jetson hardware handy, so I can't reproduce your error.  You an try

`gst-launch-1.0 -v nvarguscamerasrc ! nvvidconv ! video/x-raw,format=I420,width=1280,height=720 ! queue !  fakesink`

If it reports element not found, try

`gst-inspect-1.0` 

and check the elements you are using are built and installed properly.

**Comment by CeeBeeEh** [comment]
I'm getting this error also. I'm familiar with gstreamer but cannot find the source of the problem. I'm running this on x86 to no avail. I've removed the nvvideoconvert plugin from the pipeline description. Basically, my pipeline being tested with gst-launch-1.0 works fine. It just won't work with gstd.

**Comment by fischer** [comment]
cbstryker, please provide details of the problem so we can provide a detailed answer.

Q1 ) What is the exact gst-launch command you are running successfully?

Q2 ) What are the exact gstd / gstd-client commands you are running and paste in the failed output as well.

Q3 ) What is the host OS and what version of gst you running?

**Comment by barisduzenli** [comment]
Hello Mr Fischer,

I have Jetson Nano + RPI V2 CSI Camera + Logitech c270 Usb Webcam (No more camera is connected)
I am using Ubuntu 18.04 default jetson nano image.
I want to realize your GTC-2020-Demo.
I have installed Gstd + gstd-interpipe and I checked with gst-inspect-1.0 interpipe command. It returns;
Plugin Details:
  Name                     interpipe
  Description              Elements to communicate buffers across pipelines
  Filename                 /usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstinterpipe.so
  Version                  1.1.3
  License                  LGPL
  Source module            gst-interpipe
  Binary package           GstInterpipe
  Origin URL               http://www.ridgerun.com

  interpipesink: Internal pipeline sink
  interpipesrc: Inter pipeline source

  2 features:
  +-- 2 elements
At this point I thought all dependencies of the GTC-2020 demo is okey.

Then I am going the GTC-2020-demo/python-example directory in Terminal, and open two tap. One for DISPLAY=:0 gstd -D command to start gstd server. The other one is for ./media-server.py command to start the sequence.

I got @Server Teminal Side;
**baris@baris-desktop:~/Documents/gtc-2020-demo/python-example$ DISPLAY=:0 gstd -D 
Gstd version 0.11.3
Copyright (C) 2015-2020 RidgeRun (https://www.ridgerun.com)

0:00:31.287045355  9942   0x55bcdca990 ERROR           gstdpipeline gstd_pipeline.c:511:gstd_pipeline_create:<GstdPipeline@0x7fa810f910> Unable to create pipeline: no element "nvvideoconvert"
0:00:31.287132805  9942   0x55bcdca990 ERROR               gstdlist gstd_list.c:233:gstd_list_create:<GstdList@0x55bcca8d80> Could not create the resource  "camera0_rgba_nvmm" on "pipelines"**

@Client Terminal Side;
**baris@baris-desktop:~/Documents/gtc-2020-demo/python-example$ ./media-server.py Creating pipeline: camera0
Creating pipeline: camera0_rgba_nvmm
Traceback (most recent call last):
  File "./media-server.py", line 46, in <module>
    camera0_rgba_nvmm = PipelineEntity(client, 'camera0_rgba_nvmm', 'interpipesrc listen-to=camera0 ! video/x-raw,format=YUY2,width=1280,height=720 ! videoconvert ! video/x-raw,format=NV12,width=1280,height=720 ! nvvideoconvert ! video/x-raw(memory:NVMM),format=RGBA,width=1280,height=720 ! queue ! interpipesink name=camera0_rgba_nvmm forward-events=true forward-eos=true sync=false caps=video/x-raw(memory:NVMM),format=RGBA,width=1280,height=720,pixel-aspect-ratio=1/1,interlace-mode=progressive,framerate=30/1')
  File "./media-server.py", line 13, in __init__
    self._client.pipeline_create(self._name, self._description)
  File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 830, in pipeline_create
    self._send_cmd_line(['pipeline_create'] + parameters)
  File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 232, in _send_cmd_line
    result['code'])
pygstc.gstcerror.GstdError: ('Bad pipeline description', 2)**

I have tried 2 usb, 2csi, 1csi+1usb versions by changing create camera pipelines section of media-server.py file.

I am using nvargussrc and v4l2src device=/dev/video*.

Especially, I tried to fix hardware to your 2 camera configuration. Therefore, the media-server.py is same as in the  master repository.

# Create camera pipelines
camera0 = PipelineEntity(client, 'camera0', 'v4l2src device=/dev/video1 ! video/x-raw,format=YUY2,width=1280,height=720 ! interpipesink name=camera0 forward-events=true forward-eos=true sync=false')
pipelines_base.append(camera0)

camera0_rgba_nvmm = PipelineEntity(client, 'camera0_rgba_nvmm', 'interpipesrc listen-to=camera0 ! video/x-raw,format=YUY2,width=1280,height=720 ! videoconvert ! video/x-raw,format=NV12,width=1280,height=720 ! nvvideoconvert ! video/x-raw(memory:NVMM),format=RGBA,width=1280,height=720 ! queue ! interpipesink name=camera0_rgba_nvmm forward-events=true forward-eos=true sync=false caps=video/x-raw(memory:NVMM),format=RGBA,width=1280,height=720,pixel-aspect-ratio=1/1,interlace-mode=progressive,framerate=30/1')
pipelines_base.append(camera0_rgba_nvmm)

camera1 = PipelineEntity(client, 'camera1', 'nvarguscamerasrc ! nvvidconv ! video/x-raw,format=I420,width=1280,height=720 ! queue ! interpipesink name=camera1 forward-events=true forward-eos=true sync=false')
pipelines_base.append(camera1)

camera1_rgba_nvmm = PipelineEntity(client, 'camera1_rgba_nvmm', 'interpipesrc listen-to=camera1 ! video/x-raw,format=I420,width=1280,height=720 ! nvvideoconvert ! video/x-raw(memory:NVMM),format=RGBA,width=1280,height=720 ! interpipesink name=camera1_rgba_nvmm forward-events=true forward-eos=true sync=false caps=video/x-raw(memory:NVMM),format=RGBA,width=1280,height=720,pixel-aspect-ratio=1/1,interlace-mode=progressive,framerate=30/1')
pipelines_base.append(camera1_rgba_nvmm)

# Create Deepstream pipeline with 4 cameras processing
deepstream = PipelineEntity(client, 'deepstream', 'interpipesrc listen-to=camera0_rgba_nvmm ! nvstreammux0.sink_0 interpipesrc listen-to=camera0_rgba_nvmm ! nvstreammux0.sink_1 interpipesrc listen-to=camera1_rgba_nvmm ! nvstreammux0.sink_2 interpipesrc listen-to=camera1_rgba_nvmm ! nvstreammux0.sink_3 nvstreammux name=nvstreammux0 batch-size=4 batched-push-timeout=40000 width=1280 height=720 ! queue ! nvinfer batch-size=4 config-file-path=../deepstream-models/config_infer_primary_4_cameras.txt ! queue ! nvtracker ll-lib-file=../deepstream-models/libnvds_mot_klt.so enable-batch-process=true ! queue ! nvmultistreamtiler width=1280 height=720 rows=2 columns=2 ! nvvideoconvert ! nvdsosd ! queue ! interpipesink name=deep forward-events=true forward-eos=true sync=false')
pipelines_base.append(deepstream)
